server.port=8081
spring.application.name=users

spring.datasource.url=jdbc:postgresql://monitoringdatabase.postgres.database.azure.com:5432/eventticketing?sslmode=require
spring.datasource.username=moutia
spring.datasource.password=azertyAZERTY123@
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
logging.level.org.hibernate.orm.jdbc.bind=trace

jwt.secret=8f3b9c2a7e1d4f6b0a9c8e7d6f5b4a3c2e1d0f9b8a7c6e5d4f3b2a1c0e9d8f7b
jwt.expiration-ms=3600000

management.endpoints.web.exposure.include=health,info,prometheus
management.metrics.tags.application=events-service