server.port=8081
spring.application.name=users
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/events
spring.datasource.username=postgres
spring.datasource.password=dev
logging.level.org.hibernate.orm.jdbc.bind=trace

jwt.secret=8f3b9c2a7e1d4f6b0a9c8e7d6f5b4a3c2e1d0f9b8a7c6e5d4f3b2a1c0e9d8f7b
jwt.expiration-ms=3600000