apiVersion: apps/v1
kind: Deployment
metadata:
  name: users

spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
  
    spec:
      containers:
        - name: users
          image: eventticketingacr2026.azurecr.io/users-service:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081