server.port=8080
spring.application.name=APIGateway

spring.cloud.gateway.server.webmvc.routes[0].id=users
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/users/**

spring.cloud.gateway.server.webmvc.routes[1].id=events
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/events/**

management.endpoints.web.exposure.include=gateway
management.endpoint.gateway.enabled=true

debug=true