apiVersion: apps/v1
kind: Deployment

metadata:
  name : event

spec:
  replicas: 1

  selector:
    matchLabels:
      app: event

  template:
    metadata:
      labels:
        app: event

    spec:
      containers:
        - name: event
          image: eventticketingacr2026.azurecr.io/event-service:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081


