apiVersion: apps/v1
kind: Deployment

metadata:
  name : frontend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: frontend
  
  template:
    metadata:
      labels:
        app: frontend
  
    spec:
      containers:
        - name : frontend
          image: eventticketingacr2026.azurecr.io/frontend:v3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80