spring.application.name=ManageEvents
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url = jdbc:postgresql:event-db:5432/events
spring.datasource.username= postgres
spring.datasource.password = dev