server.port=8082
spring.application.name=ManageEvents
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://monitoringdatabase.postgres.database.azure.com:5432/eventticketing?sslmode=require
spring.datasource.username=moutia
spring.datasource.password=azertyAZERTY123@
spring.datasource.driver-class-name=org.postgresql.Driver

management.endpoints.web.exposure.include=health,info,prometheus
management.metrics.tags.application=events-service